import type {
  Companion,
  DishRecord,
  Restaurant,
  Tag,
  VisitRecord,
  WishlistItem,
} from "../types/models";

const now = "2026-06-22T09:00:00.000Z";

export const sampleRestaurants: Restaurant[] = [
  {
    id: "restaurant-hotpot-001",
    name: "蓉城巷子火锅",
    branchName: "玉林店",
    category: "火锅",
    address: "成都市武侯区玉林东路 18 号",
    district: "武侯区",
    businessArea: "玉林",
    latitude: 30.6298,
    longitude: 104.0566,
    source: "朋友推荐",
    tags: ["牛油锅底", "适合聚餐"],
    colorToken: "orange",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-sichuan-002",
    name: "锦官小院",
    branchName: "宽窄巷子店",
    category: "川菜",
    address: "成都市青羊区长顺上街 99 号",
    district: "青羊区",
    businessArea: "宽窄巷子",
    latitude: 30.6693,
    longitude: 104.055,
    source: "路过",
    tags: ["家常川菜", "环境安静"],
    colorToken: "blue",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-chuanchuan-003",
    name: "冒椒巷串串",
    branchName: "建设路店",
    category: "串串",
    address: "成都市成华区建设南路 7 号",
    district: "成华区",
    businessArea: "建设路",
    latitude: 30.6685,
    longitude: 104.1036,
    source: "小红书收藏",
    tags: ["夜宵", "麻辣"],
    colorToken: "pink",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-coffee-004",
    name: "少城晨光咖啡",
    branchName: "泡桐树街店",
    category: "咖啡",
    address: "成都市青羊区泡桐树街 24 号",
    district: "青羊区",
    businessArea: "少城",
    latitude: 30.6681,
    longitude: 104.0531,
    source: "散步发现",
    tags: ["拿铁", "适合看书"],
    colorToken: "blue",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-dessert-005",
    name: "桂花巷甜品铺",
    category: "甜品",
    address: "成都市锦江区镋钯街 39 号",
    district: "锦江区",
    businessArea: "太古里",
    latitude: 30.6532,
    longitude: 104.0857,
    source: "朋友推荐",
    tags: ["桂花", "下午茶"],
    colorToken: "pink",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-noodle-006",
    name: "东门担担面",
    branchName: "牛市口店",
    category: "面馆",
    address: "成都市锦江区海椒市街 12 号",
    district: "锦江区",
    businessArea: "牛市口",
    latitude: 30.6435,
    longitude: 104.1052,
    source: "早餐清单",
    tags: ["担担面", "快手午餐"],
    colorToken: "orange",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-bbq-007",
    name: "府河边烧烤",
    branchName: "九眼桥店",
    category: "烧烤",
    address: "成都市武侯区致民东路 6 号",
    district: "武侯区",
    businessArea: "九眼桥",
    latitude: 30.6411,
    longitude: 104.087,
    source: "同事推荐",
    tags: ["夜宵", "烤五花"],
    colorToken: "orange",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "restaurant-snack-008",
    name: "人民公园钟水饺",
    category: "小吃",
    address: "成都市青羊区祠堂街 9 号",
    district: "青羊区",
    businessArea: "人民公园",
    latitude: 30.6594,
    longitude: 104.0588,
    source: "老成都清单",
    tags: ["钟水饺", "甜水面"],
    colorToken: "pink",
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleVisitRecords: VisitRecord[] = [
  {
    id: "visit-001",
    restaurantId: "restaurant-hotpot-001",
    visitDate: "2026-06-18",
    mealPeriod: "晚餐",
    companions: ["阿宁", "小周"],
    diningPurpose: "朋友聚餐",
    totalCost: 356,
    averageCost: 119,
    peopleCount: 3,
    overallRating: 4.7,
    tasteRating: 4.8,
    environmentRating: 4.3,
    serviceRating: 4.5,
    valueRating: 4.4,
    revisitStatus: "愿意复访",
    queueWorthiness: "值得排队",
    recommendedFor: ["爱吃辣的朋友", "周末聚餐"],
    tags: ["牛油锅底", "毛肚好吃"],
    summary: "锅底很香，毛肚和鸭血都稳，下次还想带朋友来。",
    notes: "排队约 25 分钟，建议早点到。",
    photoIds: [],
    createdAt: "2026-06-18T13:00:00.000Z",
    updatedAt: "2026-06-18T13:00:00.000Z",
  },
  {
    id: "visit-002",
    restaurantId: "restaurant-sichuan-002",
    visitDate: "2026-06-15",
    mealPeriod: "午餐",
    companions: ["妈妈"],
    diningPurpose: "家庭聚餐",
    totalCost: 188,
    averageCost: 94,
    peopleCount: 2,
    overallRating: 4.5,
    tasteRating: 4.6,
    environmentRating: 4.7,
    serviceRating: 4.4,
    valueRating: 4.2,
    revisitStatus: "愿意复访",
    queueWorthiness: "不用排队更好",
    recommendedFor: ["带家人", "清淡口味朋友"],
    tags: ["宫保鸡丁", "安静"],
    summary: "菜味道稳，环境比想象中清爽，适合慢慢吃一顿。",
    photoIds: [],
    createdAt: "2026-06-15T05:30:00.000Z",
    updatedAt: "2026-06-15T05:30:00.000Z",
  },
  {
    id: "visit-003",
    restaurantId: "restaurant-chuanchuan-003",
    visitDate: "2026-06-12",
    mealPeriod: "夜宵",
    companions: ["小周"],
    diningPurpose: "朋友聚餐",
    totalCost: 132,
    averageCost: 66,
    peopleCount: 2,
    overallRating: 4.2,
    tasteRating: 4.4,
    environmentRating: 3.8,
    serviceRating: 4,
    valueRating: 4.5,
    revisitStatus: "看情况",
    queueWorthiness: "不用排队更好",
    recommendedFor: ["夜宵", "重口味"],
    tags: ["串串", "夜宵"],
    summary: "味道够麻够辣，环境热闹，适合突然想吃夜宵的时候。",
    photoIds: [],
    createdAt: "2026-06-12T15:30:00.000Z",
    updatedAt: "2026-06-12T15:30:00.000Z",
  },
  {
    id: "visit-004",
    restaurantId: "restaurant-coffee-004",
    visitDate: "2026-06-09",
    mealPeriod: "下午茶",
    companions: [],
    diningPurpose: "一个人",
    totalCost: 42,
    averageCost: 42,
    peopleCount: 1,
    overallRating: 4.6,
    tasteRating: 4.5,
    environmentRating: 4.9,
    serviceRating: 4.6,
    valueRating: 4.1,
    revisitStatus: "愿意复访",
    queueWorthiness: "不用排队更好",
    recommendedFor: ["一个人看书", "下午办公"],
    tags: ["拿铁", "安静"],
    summary: "窗边座位很舒服，咖啡干净，适合写东西。",
    photoIds: [],
    createdAt: "2026-06-09T08:40:00.000Z",
    updatedAt: "2026-06-09T08:40:00.000Z",
  },
  {
    id: "visit-005",
    restaurantId: "restaurant-dessert-005",
    visitDate: "2026-05-29",
    mealPeriod: "下午茶",
    companions: ["阿宁"],
    diningPurpose: "约会",
    totalCost: 78,
    averageCost: 39,
    peopleCount: 2,
    overallRating: 4.3,
    tasteRating: 4.4,
    environmentRating: 4.5,
    serviceRating: 4.2,
    valueRating: 4,
    revisitStatus: "看情况",
    queueWorthiness: "不用排队更好",
    recommendedFor: ["甜品脑袋", "太古里逛街"],
    tags: ["桂花", "甜品"],
    summary: "桂花香明显，甜度刚好，逛累了坐一会儿很合适。",
    photoIds: [],
    createdAt: "2026-05-29T08:10:00.000Z",
    updatedAt: "2026-05-29T08:10:00.000Z",
  },
];

export const sampleDishRecords: DishRecord[] = [
  {
    id: "dish-001",
    visitId: "visit-001",
    name: "鲜毛肚",
    category: "火锅菜",
    price: 48,
    rating: 4.8,
    recommendationStatus: "必点",
    notes: "脆，涮十秒刚好。",
    photoIds: [],
    createdAt: "2026-06-18T13:00:00.000Z",
    updatedAt: "2026-06-18T13:00:00.000Z",
  },
  {
    id: "dish-002",
    visitId: "visit-001",
    name: "鸭血",
    category: "火锅菜",
    price: 22,
    rating: 4.6,
    recommendationStatus: "推荐",
    photoIds: [],
    createdAt: "2026-06-18T13:00:00.000Z",
    updatedAt: "2026-06-18T13:00:00.000Z",
  },
  {
    id: "dish-003",
    visitId: "visit-002",
    name: "宫保鸡丁",
    category: "热菜",
    price: 58,
    rating: 4.7,
    recommendationStatus: "推荐",
    photoIds: [],
    createdAt: "2026-06-15T05:30:00.000Z",
    updatedAt: "2026-06-15T05:30:00.000Z",
  },
  {
    id: "dish-004",
    visitId: "visit-003",
    name: "牛肉串串",
    category: "串串",
    price: 2,
    rating: 4.4,
    recommendationStatus: "推荐",
    photoIds: [],
    createdAt: "2026-06-12T15:30:00.000Z",
    updatedAt: "2026-06-12T15:30:00.000Z",
  },
  {
    id: "dish-005",
    visitId: "visit-004",
    name: "冰拿铁",
    category: "咖啡",
    price: 32,
    rating: 4.5,
    recommendationStatus: "推荐",
    photoIds: [],
    createdAt: "2026-06-09T08:40:00.000Z",
    updatedAt: "2026-06-09T08:40:00.000Z",
  },
];

export const sampleWishlistItems: WishlistItem[] = [
  {
    id: "wishlist-001",
    restaurantName: "猛追湾豆花饭",
    category: "小吃",
    district: "成华区",
    businessArea: "猛追湾",
    source: "朋友推荐",
    priority: "高",
    notes: "想试豆花和烧白。",
    tags: ["午餐", "老店"],
    status: "想吃",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "wishlist-002",
    restaurantName: "桐梓林泰式小馆",
    category: "其他",
    district: "武侯区",
    businessArea: "桐梓林",
    source: "收藏夹",
    priority: "中",
    tags: ["周末"],
    status: "想吃",
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleCompanions: Companion[] = [
  { id: "companion-001", name: "阿宁", createdAt: now, updatedAt: now },
  { id: "companion-002", name: "小周", createdAt: now, updatedAt: now },
  { id: "companion-003", name: "妈妈", createdAt: now, updatedAt: now },
];

export const sampleTags: Tag[] = [
  { id: "tag-001", name: "夜宵", color: "#e9783f", type: "visit", createdAt: now, updatedAt: now },
  { id: "tag-002", name: "适合聚餐", color: "#a8d8ea", type: "restaurant", createdAt: now, updatedAt: now },
  { id: "tag-003", name: "安静", color: "#f4b8c4", type: "visit", createdAt: now, updatedAt: now },
];
